#[path = "inspect_disks/index.rs"]
pub mod inspect_disks;
#[path = "measure_bandwidth/index.rs"]
pub mod measure_bandwidth;
#[path = "query_local_ai/index.rs"]
pub mod query_local_ai;
#[path = "read_appliance_log/index.rs"]
pub mod read_appliance_log;
#[path = "read_logs/index.rs"]
pub mod read_logs;
#[path = "read_receipts/index.rs"]
pub mod read_receipts;
#[path = "report_health/index.rs"]
pub mod report_health;
#[path = "report_identity/index.rs"]
pub mod report_identity;
#[path = "report_links/index.rs"]
pub mod report_links;
#[path = "report_profile/index.rs"]
pub mod report_profile;
#[path = "report_sources/index.rs"]
pub mod report_sources;
#[path = "test_drive/index.rs"]
pub mod test_drive;
#[path = "write_appliance_log/index.rs"]
pub mod write_appliance_log;

#[path = "manage_child_device/index.rs"]
pub mod manage_child_device;
#[path = "pin_device_address/index.rs"]
pub mod pin_device_address;
#[path = "whitelist_device/index.rs"]
pub mod whitelist_device;

#[path = "annotate_device/index.rs"]
pub mod annotate_device;
#[path = "claim_device_identity/index.rs"]
pub mod claim_device_identity;
#[path = "control_resolver/index.rs"]
pub mod control_resolver;
#[path = "list_network_devices/index.rs"]
pub mod list_network_devices;
#[path = "name_device/index.rs"]
pub mod name_device;
