//! Enumerable C2 Rust serve primitive registry.
// Names are concrete leaf operations, never generic router façades.
pub static RUST_PRIMITIVES: &[&str] = &[
    "health",
    "identity",
    "profile",
    "admittance",
    "attendance",
    "staff",
    "discovery",
    "caduceus_staff_receipt",
    "appliance_report_read",
    "appliance_stats_read",
    "bandwidth_measure_read",
    "log_receipts_read",
    "log_reflect_mutate",
    "log_clear_mutate",
    "log_write_mutate",
    "projector_power_mutate",
    "projector_products_read",
    "projector_scan_mutate",
    "settings_appearance_read_mutate",
    "settings_datetime_read_mutate",
    "settings_default_apps_read_mutate",
    "settings_display_read_mutate",
    "settings_input_read_mutate",
    "settings_notifications_read_mutate",
    "settings_sound_read_mutate",
    "appliance_service_control",
    "python_library_list",
    "python_library_run",
    "python_library_status",
    "network_device_claim_witness",
    "network_device_claim_public_shape",
    "network_dns_route_action_witness",
    "network_dns_public_receipt_shape",
    "network_firewall_policy_input_witness",
    "network_firewall_status_refusal_shape",
    "storage_vault_unlock_witness",
    "storage_vault_unlock_public_shape",
];
pub fn contains(name: &str) -> bool {
    RUST_PRIMITIVES.contains(&name)
}
