pub mod cartridges;
pub mod cert;
pub mod coronatio;
pub use crate::staff_commands::manage_child_device as child_device;
pub mod config;
pub use crate::staff_commands::annotate_device as network_notes;
pub use crate::staff_commands::claim_device_identity as network_identity;
pub use crate::staff_commands::control_resolver as dns_control;
pub use crate::staff_commands::inspect_disks as disk;
pub use crate::staff_commands::list_network_devices as network;
pub use crate::staff_commands::list_network_devices as network_read;
pub use crate::staff_commands::measure_bandwidth as speedtest;
pub use crate::staff_commands::name_device as dns;
pub use crate::staff_commands::pin_device_address as dhcp;
pub use crate::staff_commands::test_drive as drive_test;
pub use crate::staff_commands::whitelist_device as firewall;
pub mod gui;
pub use crate::staff_commands::report_health as health;
pub mod harmonia_update;
pub mod help;
pub mod homeserver_sbin;
pub use crate::staff_commands::report_identity as identity;
pub use crate::staff_commands::write_appliance_log as hyalos;
pub mod legacy_sbin;
pub use crate::staff_commands::query_local_ai as local_ai;
pub use crate::staff_commands::read_logs as logs;
pub use crate::staff_commands::report_links as linker;
pub mod pjlink;
pub use crate::staff_commands::report_profile as profile;
pub mod profile_module;
pub use crate::staff_commands::read_receipts as receipts;
pub mod serve;
pub mod settings;
pub use crate::staff_commands::report_sources as source_map;
pub mod staff;
pub mod sync;

pub mod update;
pub mod vault;
