pub mod cartridges;
pub mod cert;
pub mod coronatio;
pub use crate::staff_commands::manage_child_device as child_device;
pub mod config;
pub use crate::staff_commands::pin_device_address as dhcp;
pub use crate::staff_commands::inspect_disks as disk;
pub use crate::staff_commands::measure_bandwidth as speedtest;
pub use crate::staff_commands::test_drive as drive_test;
pub mod dns;
pub use crate::staff_commands::whitelist_device as firewall;
pub mod gui;
pub use crate::staff_commands::report_health as health;
pub mod harmonia_update;
pub mod help;
pub mod homeserver_sbin;
pub use crate::staff_commands::write_appliance_log as hyalos;
pub use crate::staff_commands::report_identity as identity;
pub mod legacy_sbin;
pub use crate::staff_commands::report_links as linker;
pub use crate::staff_commands::query_local_ai as local_ai;
pub use crate::staff_commands::read_logs as logs;
pub mod network;
pub mod network_identity;
pub mod network_notes;
pub mod network_read;
pub mod pjlink;
pub use crate::staff_commands::report_profile as profile;
pub mod profile_module;
pub use crate::staff_commands::read_receipts as receipts;
pub mod serve;
pub mod settings;
pub use crate::staff_commands::report_sources as source_map;
pub mod staff;
pub mod sync;
pub mod tailscale;
pub mod time;
pub mod update;
pub mod vpn;
pub mod vault;
