#[path = "../gate/index.rs"]
pub mod gate;
#[path = "../protocol/index.rs"]
pub mod protocol;
#[path = "../routes/mod.rs"]
pub mod routes;
#[path = "lib/mod.rs"]
pub mod shared;
#[path = "stats.rs"]
pub mod stats;
pub use routes::cli::run;
